name: maintemplatev2
description: A new Flutter project.
publish_to: none

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=2.10.0-0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # Responsive Design
  # navigation_rail: ^1.0.4
  responsive_builder:
  #  responsive_scaffold: ^1.3.0+2
  #  master_detail_scaffold: ^1.1.1+1
  #  rflutter_alert: ^1.1.0

  # mod_write:
  #   path: ../../mod-write/client
  # mod_chat:
  #   path: ../../mod-chat/client
  #mod_chat_beta:
  #  path: ../../mod-chat-beta/client
  # mod_ion:
  #   path: ../../mod-ion/client
  # mod_geo:
  #   path: ../../mod-geo/client
  # mod_session:
  #   path: ../../mod-session/client
  # mod_main:
  #   path: ../../mod-main/client
  # mod_account:
  #   path: ../../mod-account/client
  # mod_kanban:
  #   path: ../../mod-kanban/client
  # sys_core:
  # git:
  # url: git://github.com/getcouragenow/sys.git
  # path: sys-core/service/flu

  mod_disco:
    #    git:
    #      url: git://github.com/getcouragenow/mod.git
    #      path: mod-disco/service/flu
    #      ref: cfafd56bf659673163d699fc761e4a73d6cb8bdd
    path: ../../../../../mod/mod-disco/service/flu
  bootstrapper:
    #    git:
    #      url: git://github.com/getcouragenow/main.git
    #      path: deploy/bootstrapper/service/flu
    #      ref: e940e1cde842537c62580a467b3e489bfa84085e
    path: ../../../bootstrapper/service/flu

  #sys_core:
  #  git:
  #    url: git://github.com/getcouragenow/core-runtime.git
  #    path: sys-core/client
  #    ref: master

  # Architectural packages
  provider: ^4.3.2
  provider_architecture: ^1.1.1+1
  grpc: ^2.8.0
  protobuf: ^1.1.0
  intl: ^0.17.0-nullsafety.2
  #  get_it: ^3.1.0
  #  equatable:
  meta:
  #  flutter_modular: ^3.0.0-nullsafety.20
  flutter_modular: ^3.0.0-0
  flutter_platform_widgets: ^1.0.0-nullsafety.0
  # font_awesome_flutter:
  cupertino_icons: ^1.0.0
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  # TODO use official package when it supports nullsafety
  intl_translation:
    git:
      url: https://github.com/gutterbacon/intl_translation
      ref: 4c5e4638bf23444ab7d5d60f00f4319f37dee98c
  #  intl_translation: ^0.17.10+1
  build_runner: ^1.10.2
  hive_generator: ^0.8.2
  json_serializable: ^3.2.3
  flutter_launcher_icons: ^0.8.1

flutter_icons:
  android: true
  ios: true
  image_path: 'assets/icon/placeholder.png'

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - ./i18n/
    - assets/env.json
    - assets/icon/placeholder.png
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
