name: build-v2

on:
  pull_request:
    branches:
      - '*'

jobs:
  all:
    name: build-v2
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest ]
        go-version: [ 1.15.6 ]
        target: [ "this-all", ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
        id: go

      - name: Setup Go binary path
        shell: bash
        run: |
          echo "GOPATH=${{ github.workspace }}" >> $GITHUB_ENV
          echo "${{ github.workspace }}/bin" >> $GITHUB_PATH

      - name: Git line endings
        shell: bash
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: '14.x'

      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      - name: Check out main code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          path: ${{ github.workspace }}/go/src/github.com/amplify-cms/main

      - name: Check out the shared repo code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: master
          repository: amplify-cms/shared
          path: ${{ github.workspace }}/go/src/github.com/amplify-cms/shared

      - name: Check out the sys-share code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: master
          repository: amplify-cms/sys-share
          path: ${{ github.workspace }}/go/src/github.com/amplify-cms/sys-share

      - name: Check out the mod code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: master
          repository: amplify-cms/mod
          path: ${{ github.workspace }}/go/src/github.com/amplify-cms/mod

      - name: Check out the sys code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: master
          repository: amplify-cms/sys
          path: ${{ github.workspace }}/go/src/github.com/amplify-cms/sys

      - name: make ${{ matrix.target }}
        run: |
          # workaround for https://github.com/actions/setup-go/issues/14
          #export GOPATH=${GITHUB_WORKSPACE}/go
          #export PATH=$PATH:$GOPATH/bin
          make $target
        working-directory: ${{ github.workspace }}/go/src/github.com/amplify-cms/main
        env:
          CONFIG_PASSWORD: ${{ secrets.CONFIG_PASSWORD }}
          CAROOT: ${{ github.workspace }}/certs
          target: ${{ matrix.target }}

